version: '2.3'
services:
  dqlite-bench:
    image: jujusolutions/dqlite-bench:latest
    build:
      context: ../..
      dockerfile: ./scripts/dqlite-bench/Dockerfile
    ports:
      - 3333:3333
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
